name: WebDriverIO CI - Android

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18' # Specify your Node.js version

    - name: Install dependencies
      run: npm install 

    - name: Run WebDriver tests
      run: npm run android.app.headless.cucumber

    - name: Generate Allure Report 
      if: always() # Generate report even if tests fail
      run: npm run report # Or your command to generate reports

    - name: Upload Test Reports/Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: test-results # Name of the artifact
        path: |
          ./allure-results # Path to your test reports or other artifacts
          ./screenshots # Example for screenshots
        retention-days: 7 # Optional: Set retention period for artifacts