name: WebDriverIO CI - IOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18' # Or your preferred Node.js version
    - name: Install dependencies
      run: npm install
    - name: Run WebdriverIO tests
      run: npm test