name: WebdriveIo on BrowserStack

on:
  push:
    branches: main
  pull_request:
    branches: main
  workflow_dispatch:

jobs:
  test-browserstack-android:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    env:
      BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
      BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
      PLATFORM: android

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run Android tests on BrowserStack
        run: npx wdio run ./config/wdio.browserstack.conf.ts

      - name: Generate Allure Report
        if: always()
        run: npm run report 
        continue-on-error: true

      - name: Upload Allure Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report-android
          path: reports/allure-report